### ISSUE TITLE
--acfix in rapidtide does not work

### ISSUE THREAD

**Issue by themeo** [bbfrederick/rapidtide#115]
**Describe the bug**
After running rapidtide from a singularity container (2.6.0), I get the following error:

> *********************
> Pass number 1
> checking reference regressor autocorrelation properties
> searching for sidelobes with amplitude > 0.1 with abs(lag) < 30.0 s
> 
> 
> WARNING: check_autocorrelation found bad sidelobe at 10.414616713318386 seconds (0.09601889608872338 Hz)...
> Removing sidelobe
> subjecting lag times to modulus
> removing spectral component at sidelobe frequency
> Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/rapidtide", line 23, in <module>
>     rapidtide_workflow.rapidtide_main(rapidtide_parser.process_args(inputargs=None))
>   File "/usr/local/miniconda/lib/python3.11/site-packages/rapidtide/workflows/rapidtide.py", line 1528, in rapidtide_main
>     transferfunc=optiondict["transferfunc"],
>                  ~~~~~~~~~~^^^^^^^^^^^^^^^^
> KeyError: 'transferfunc'
> 

**To Reproduce**
This is my call:
`singularity exec /home/language/jaksze/rapidtide-2.6.0.simg rapidtide epi.nii.gz output --filterband lfo --passes 3 --nprocs 24 --noprogressbar --acfix`

**Comment by themeo** [comment]
I confirm there is now no error when using the option, thanks for the fix!
The computation takes much longer than with other options but that I assume
is expected.

**Comment by themeo** [comment]
You are right, when I reran it, the difference was only 17% longer when including --acfix.

**Comment by bbfrederick** [comment]
Glad it worked!
