### ISSUE TITLE
Tidepool cannot visualize lag times

### ISSUE THREAD

**Issue by ezgirmak** [bbfrederick/rapidtide#15]
Hello,

I ran rapidtide2 on a timeseries volume data, that ran fine. I tried visualizing it using tidepool, initially I had to install pyqtgraph and PyQt5 both pretty simple pip install's. After that, the gui comes up and asks to load specific lagtime.nii.gz when I tried to load the lag file it gave the following error: 

```
overlay name:          p_lt_0p001_mask
    label:             p_lt_0p001_mask
    filename:          /mnt/viscog/FineLab/V2B/156334/rapidtide/rapidtide--despecklepasses=4_p_lt_0p001_mask.nii.gz
    namebase:          rapidtide--despecklepasses=4_
    xdim:              113
    ydim:              136
    zdim:              113
    tdim:              1
    isMNI:             True
    toffset:           0.0
    tr:                1.0
    min:               0.0
    max:               1.0
    robustmin:         0.995
    robustmax:         0.995
    dispmin:           0.995
    dispmax:           0.995
    data shape:        (113, 136, 113)
    masked data shape: (113, 136, 113)
    geometric mask is set
    functional mask is set
['lagmask', 'p_lt_0p050_mask', 'p_lt_0p010_mask', 'p_lt_0p005_mask', 'p_lt_0p001_mask']
fsldir set to  /usr/share/fsl/5.0
no geometric mask loaded
['R_proximal_ACA', 'R_middle_ACA', 'R_distal_ACA', 'R_proximal_MCA', 'R_middle_MCA', 'R_distal_MCA', 'R_proximal_PCA', 'R_middle_PCA', 'R_distal_PCA', 'L_proximal_ACA', 'L_middle_ACA', 'L_distal_ACA', 'L_proximal_MCA', 'L_middle_MCA', 'L_distal_MCA', 'L_proximal_PCA', 'L_middle_PCA', 'L_distal_PCA']
Traceback (most recent call last):
  File "/mnt/home/yucel/.conda/envs/py3/bin/tidepool", line 4, in <module>
    __import__('pkg_resources').run_script('rapidtide==1.6.0', 'tidepool')
  File "/mnt/home/yucel/.conda/envs/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/home/yucel/.conda/envs/py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/mnt/home/yucel/.conda/envs/py3/lib/python3.6/site-packages/rapidtide-1.6.0-py3.6.egg/EGG-INFO/scripts/tidepool", line 1929, in <module>
    main()
  File "/mnt/home/yucel/.conda/envs/py3/lib/python3.6/site-packages/rapidtide-1.6.0-py3.6.egg/EGG-INFO/scripts/tidepool", line 1621, in main
    if atlasniftiname is not None:
UnboundLocalError: local variable 'atlasniftiname' referenced before assignment
```

Thanks!

**Comment by bbfrederick** [comment]
Hi!  Sorry I just saw this now - I think my notifications must have gotten turned off.

My first thought is that for whatever reasons your atlas files may not be getting installed as expected (not a lot of people use this, so it may not be fully working.  By "not a lot of people" I mean "I wasn't aware anybody but me used this").

I'll look at this more in depth, but as a workaround - I'm not sure having an '=' in the filename (as in name base: rapidtide--despecklepasses=4_) isn't going to cause some internal choking in processing of names.  Can you try renaming the output files?

**Comment by ezgirmak** [comment]
Hi Blaise! Sorry for the late reply, I wanted to let you know that I can now run tidepool after pulling the new code. 

Thanks a lot,
Ezgi
