### ISSUE TITLE
wiener deconvulution for response function per voxel, rapidtide2x

### ISSUE THREAD

**Issue by ZieroNLD** [bbfrederick/rapidtide#29]
**Describe the bug**
tried the wiener deconvolution option in rapidtide2x (1.9.1), unfortunately the program crashed 
is this option working at the moment?
thanks

**To Reproduce**
commandline I ran:
rapidtide2x $SUBJDIR/${SUBJ}_final_FEAT_yesAROMA_yesMO_final.feat/filtered_func_data.nii.gz $SUBJDIR/${SUBJ}_RAPIDTIDE2x_lean_p2_deconv/${SUBJ}_final_FEAT_yesAROMA_yesMO_final --datatstep=3 -T --noglm -T --regressor=$SUBJDIR/TRACES/${SUBJ}_EtCO2_trace_norm.txt --passes=2 --wiener --psdfilter --nprocs=10

**Screenshots**
from the output shown in the terminal:
>
Wiener deconvolution
Traceback (most recent call last):
  File "/home/username/anaconda3/bin/rapidtide2x", line 4, in <module>
    __import__('pkg_resources').run_script('rapidtide==1.9.0', 'rapidtide2x')
  File "/home/username/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/username/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/username/anaconda3/lib/python3.7/site-packages/rapidtide-1.9.0-py3.7.egg/EGG-INFO/scripts/rapidtide2x", line 31, in <module>
    rapidtide2x_workflow.rapidtide_main()
  File "/home/username/anaconda3/lib/python3.7/site-packages/rapidtide-1.9.0-py3.7.egg/rapidtide/workflows/rapidtide2x.py", line 2362, in rapidtide_main
    rt_floattype=rt_floattype
TypeError: wienerpass() missing 5 required positional arguments: 'r2value', 'fitcoff', 'fitNorm', 'datatoremove', and 'filtereddata'
>

**Comment by bbfrederick** [comment]
That should really be in experimental options, rather than miscellaneous.  I never really finalized that feature, and I haven't tested it for a while in the face of some internal changes.  I'll see if I can at least get it functional again, though.
