### ISSUE TITLE
pyfftw nthreads error

### ISSUE THREAD

**Issue by robbwh** [bbfrederick/rapidtide#79]
Using the most recent docker container, I am still getting an error related to using multiple threads.

Rapidtide continues running still though.

```length: 225
input freq: 0.4999997615815346
input start time: 0.000
synctime is 0.0
total probe regressor offset is 0.0
there are 225 points in the original regressor
the timepoint spacing is 2.0000009536743164
the input timecourse start time is 0.0
first fMRI point is at 0.0 seconds relative to time origin
os_fmri_x dim-0 shape: 1121
initial_fmri_x dim-0 shape: 225
filtering to arb band
RuntimeError: Undefined plan with nthreads. This is a bug
Exception ignored in: 'pyfftw.pyfftw._fftw_plan_with_nthreads_null'
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.9/site-packages/pyfftw/builders/_utils.py", line 285, in _Xfftn
    FFTW_object = pyfftw.FFTW(input_array, output_array, axes, direction,
RuntimeError: Undefined plan with nthreads. This is a bug
RuntimeError: Undefined plan with nthreads. This is a bug
Exception ignored in: 'pyfftw.pyfftw._fftw_plan_with_nthreads_null'
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.9/site-packages/pyfftw/builders/_utils.py", line 285, in _Xfftn
    FFTW_object = pyfftw.FFTW(input_array, output_array, axes, direction,
RuntimeError: Undefined plan with nthreads. This is a bug
RuntimeError: Undefined plan with nthreads. This is a bug
Exception ignored in: 'pyfftw.pyfftw._fftw_plan_with_nthreads_null'
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.9/site-packages/pyfftw/builders/_utils.py", line 285, in _Xfftn
    FFTW_object = pyfftw.FFTW(input_array, output_array, axes, direction,
RuntimeError: Undefined plan with nthreads. This is a bug
1121 1121 225 225
corrtr=0.40000019073486326
RuntimeError: Undefined plan with nthreads. This is a bug
Exception ignored in: 'pyfftw.pyfftw._fftw_plan_with_nthreads_null'
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.9/site-packages/pyfftw/builders/_utils.py", line 285, in _Xfftn
    FFTW_object = pyfftw.FFTW(input_array, output_array, axes, direction,
RuntimeError: Undefined plan with nthreads. This is a bug
RuntimeError: Undefined plan with nthreads. This is a bug
```Exception ignored in: 'pyfftw.pyfftw._fftw_plan_with_nthreads_null'

...(continues to run)

**Comment by robbwh** [comment]
I think fixed this in my personal installation by installing an earlier build of pyfftw:
https://github.com/pyFFTW/pyFFTW/issues/294

**Comment by bbfrederick** [comment]
I applied the workaround specified in the referenced thread (fell back to "pyfftw=0.13.0=py39h51d1ae8_0") to the Dockerfile.  I don't see the error running in Docker - let me know if it's working for you.

**Comment by robbwh** [comment]
really appreciate it--that seems to have fixed it!
